pipeline:
  build:
    image: golang:1.11
    environment:
      DATABASE_ADDRESS: "database:3306"
      REDIS_ADDRESS: "redis:6379"
    commands:
      - go get -d -v ./...
      - go get github.com/stretchr/testify
      - go build
      - sleep 5
      - go test -v ./...

services:
  redis:
    image: redis
  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"