pipeline:
  build:
    image: golang:1.11
    commands:
      - go get -d -v ./...
      - go get github.com/stretchr/testify
      - go build
      - go test ./...

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "go_gin_test"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"